### ISSUE TITLE
Create Icons

### ISSUE THREAD

**Issue by CorwinBurton** [CorwinBurton/NetMap#15]
Create or find free to use icons for device types

IoT device
Router
Switch
Desktop/Laptop (Macintosh/Apple)
Desktop/Laptop (Windows)
Desktop/Laptop (Linux)
iPhone/iPad
Android device

**Comment by moecollins512** [comment]
![android_phone_image](https://user-images.githubusercontent.com/31392658/30778649-4e0a11d6-a0a9-11e7-9ea6-829986b36bfd.jpg)
![iot-home](https://user-images.githubusercontent.com/31392658/30778650-4e19ae3e-a0a9-11e7-93b3-05b17b5d4835.jpg)
![iot](https://user-images.githubusercontent.com/31392658/30778651-4e1c8cda-a0a9-11e7-83e0-b00cc9dd77b7.jpg)
![ipad_image](https://user-images.githubusercontent.com/31392658/30778653-4e1f2558-a0a9-11e7-9c1d-f7f116adce8d.jpg)
![iphone_image](https://user-images.githubusercontent.com/31392658/30778652-4e1edcb0-a0a9-11e7-9e25-7327dcbfebe1.jpg)
![linux_desktop](https://user-images.githubusercontent.com/31392658/30778658-4e3f3924-a0a9-11e7-8580-1ffe98c23e20.jpeg)
![mac_desktop](https://user-images.githubusercontent.com/31392658/30778654-4e284a48-a0a9-11e7-858d-4e43214ade84.jpeg)
![router image](https://user-images.githubusercontent.com/31392658/30778655-4e2cf692-a0a9-11e7-8526-94913639b51c.png)
![switch](https://user-images.githubusercontent.com/31392658/30778656-4e340b6c-a0a9-11e7-8f34-16ed6a76c632.jpg)
![windows_desktop](https://user-images.githubusercontent.com/31392658/30778657-4e392156-a0a9-11e7-85d4-77ca8645c51f.jpeg)

**Comment by moecollins512** [comment]
Let me know if you like me to edit the images more or change anything.

**Comment by CorwinBurton** [comment]
We will want square icons that are a set size, maybe 124x124. Since Abass is doing the GUI, please coordinate with him to decide on the exact size so that they can be displayed l.

**Comment by moecollins512** [comment]
That'll work. I'll get with Abass and post on here again once done.

**Comment by moecollins512** [comment]
![android_phone_146w_124h](https://user-images.githubusercontent.com/31392658/30786549-a4c8a644-a145-11e7-88e0-c0e3f6459c25.jpg)
![desktop_154w_124h](https://user-images.githubusercontent.com/31392658/30786550-a4ca2190-a145-11e7-8da7-10f58eafaa54.jpg)
![iot_125w_124h](https://user-images.githubusercontent.com/31392658/30786548-a4c8476c-a145-11e7-8ef7-b511b77d222a.jpg)
![iot-home](https://user-images.githubusercontent.com/31392658/30786553-a4cb5754-a145-11e7-850c-7420aad75d1a.jpg)
![ipad_124w_143h](https://user-images.githubusercontent.com/31392658/30786551-a4ca395a-a145-11e7-8779-c9a899eef97c.jpg)
![iphone_124w_142h](https://user-images.githubusercontent.com/31392658/30786552-a4ca302c-a145-11e7-8c15-bc8d6ff4b5ef.jpg)
![linux_124w_103h](https://user-images.githubusercontent.com/31392658/30786556-a4d707ca-a145-11e7-8159-6ecf98621222.jpg)
![macdesktop_237w_124h](https://user-images.githubusercontent.com/31392658/30786554-a4d54b42-a145-11e7-8b89-eb7e3df066fe.jpg)
![router_173w_124h](https://user-images.githubusercontent.com/31392658/30786555-a4d5fc7c-a145-11e7-9ce1-522f0716701f.png)
![switch_155w_124h](https://user-images.githubusercontent.com/31392658/30786557-a4d76058-a145-11e7-83f4-9869a4d53108.jpg)

**Comment by moecollins512** [comment]
So I had to change the sizes and they couldn't all be 124 x 124.  So here are the sizes
Android_phone: 146w/124h
Desktop/PC: 154w/124h
iot1: 125w/124h
Ipad: 124w/142h
Iphone: 124w/103h
Linux Desktop: 124w/103h
Mac Desktop: 237w/124h
Router: 173w/124h
Switch: 155w/124h

All, 

Let me know if this works

R,
Moe
