### ISSUE TITLE
### Select programming language/framework

### ISSUE THREAD

**Issue by CorwinBurton** [CorwinBurton/NetMap#3]
* Node.js (web app)
* Java
* C++
* Python

**Comment by moecollins512** [comment]
I can assist with Java some. I haven't used C++ in a long while and I haven't used Python.

**Comment by CorwinBurton** [comment]
I'm leaning towards a web app of some sort, such as php or node.js. This will simplify interface creation, database management, and testing quite a bit.

**Comment by CorwinBurton** [comment]
Java
